# docker-compose.yml

services:
  nodered:
    build: .
    container_name: mynodered
    ports:
      - "1880:1880"
    environment:
      TZ: Europe/Athens
    volumes:
      - node_red_data:/data
    depends_on:
     minio:
      condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:1880"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks: [appnet]
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: myminio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks: [appnet]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    restart: unless-stopped

volumes:
  node_red_data:
  minio_data:

networks:
  appnet:
    name: flightsnet   # <— σταθερό όνομα δικτύου (σημαντικό για το Jenkins stage “Prep MinIO”)